In [9]:
from utils.config_parse import params as params
from load_dataset import load_dataset
from initialize_subactivity_assignments import initialize_subactivity_assignments
from embedding.init_embedding_weights import init_embedding_weights
import numpy as np

In [2]:
path2embeddingdata_folder = "/mnt/c/Users/dcsang/Documents/code_translate/BREAKFAST_EXP/breakfast_iter/intermediate/INTERMEDIATE_DATA/FINAL_breakfast_iter/coffee/experiment_k_6/v_0_s_50_e_1_nGauss_3word2vec/rand_iter_1/iterative_1"

In [3]:
W = init_embedding_weights() 

In [4]:
from utils.get_dataset_fold import get_dataset_fold

In [5]:
    Wa = W["Wa"]
    Wf = W["Wf"]

In [17]:
Wa.shape

(50, 201)

In [6]:
    __batch_size = params["embedding"]["train"]["batch_size"]
    __max_epochs = params["embedding"]["train"]["max_epochs"]

In [7]:
    print("getting training fold...\n")
    train_split = get_dataset_fold('train', path2embeddingdata_folder)
    print("getting validation fold...\n")
    vald_split = get_dataset_fold("val", path2embeddingdata_folder)

getting training fold...

getting validation fold...



In [ ]:
if vald_split["frames"]

In [14]:
Ni = train_split["frames_features"].shape[0]
max_iters = np.ceil(Ni/__batch_size) * __max_epochs
ppi = 1 #how often (in unit of epochs) to evaluate validation error and (maybe) save checkpoint
pp = np.ceil(ppi*(Ni/__batch_size)) #convert ppi from units of epoochs to units of iterations

In [23]:
Wa_Eg = np.zeros(Wa.shape)#TODO
Wf_Eg = np.zeros(Wf.shape)
raw_costs = np.zeros([np.int(max_iters), 1])
reg_costs = np.zeros([np.int(max_iters), 1])

In [26]:
__best_score = get_param('min_save_score', -1)

(325, 1)

In [27]:
    hist_iter = []
    hist_e2v  = [] #validation score
    hist_e3v  = []
    hist_e2t  = [] #training score
    hist_e3t  = []

In [28]:
    W_best = {}
    print("Starting Optimisation")

Starting Optimisation


In [48]:
batch_indices = np.random.permutation(Ni)
if Ni%__batch_size :
    padding_frames_count = __batch_size - (Ni%__batch_size)
    new_size = Ni + padding_frames_count
    batch_indices = np.resize(batch_indices, new_size)
batch_indices = batch_indices.reshape(-1, __batch_size)

In [52]:
batch_indices[0].shape

(300,)

In [54]:
bro = np.array([1,2,4,5,6,7,8])
idx = [0,5,3]
bro[idx]

array([1, 7, 5])

In [61]:
v = np.arange(4).reshape(2,2)
po = np.arange(2).reshape(2,1)
np.dot(v,po)

array([[1],
       [3]])

In [60]:
po

array([[0],
       [1]])