In [1]:
from utils.config_parse import params
from load_dataset import load_dataset
from initialize_subactivity_assignments import initialize_subactivity_assignments
from embedding.init_embedding_weights import init_embedding_weights

#TODO change g_K to subacts_count
#TODO change gt_labels to vids_frames_gt_label

In [2]:
# LOAD DATA
activity = "coffee"
path = r"/mnt/c/Users/dcsang/Documents/code_translate/DATA/breakfast_actions/formatted_data_new/"
vids_frames_features, gt_labels, vids_frames_count, g_K = load_dataset(activity, path)

Dataset Loaded Successfully


In [3]:
#RANDOM INITIALISATION OF ACTIVITY LABELS
__rho_prior = params["gmm"]["infOut"]["rho_prior"]
samples = initialize_subactivity_assignments(vids_frames_count, g_K, __rho_prior)

Uniform initialisation of subactivity labels complete


In [13]:
#EMBEDDING PART
#latent space transformation Weight: W {Wf, Wa}
W = init_embedding_weights() #this is  initParams of original code

In [14]:
path2embeddingdata_folder = "/mnt/c/Users/dcsang/Documents/code_translate/BREAKFAST_EXP/breakfast_iter/intermediate/INTERMEDIATE_DATA/FINAL_breakfast_iter/coffee/experiment_k_6/v_0_s_50_e_1_nGauss_3word2vec/rand_iter_1/iterative_1"

In [340]:
def get_path(dir_path, fold_type, data_type):
    return os.path.join(dir_path, "split_"+fold_type+"_"+data_type+".mat")
    
def get_dataset_fold(fold_type, path2data_dir):
    """fold_type: val, train or test"""
    
    meta_path = get_path(path2data_dir, fold_type, "meta")
    labels_path = get_path(path2data_dir, fold_type, "sent")
    frames_path = get_path(path2data_dir, fold_type, "img")
    
    metadata = hdf5storage.loadmat(meta_path)
    labeldata = hdf5storage.loadmat(labels_path)
    framesdata = hdf5storage.loadmat(frames_path)
    
    frames =[]
    labels_appended = []
    if framesdata["Img"]:
        #for the time being; 
        frames = np.array([framesdata["Img"][i][0][0][0][0][0] for i in range(framesdata["Img"].shape[0])])
        labels = np.array([labeldata["Text"][0][i][0][0][2].T[0] for i in range(labeldata["Text"].shape[1])])

        #making word_2_vec dimension =201
        concat = [1]
        labels_appended = np.zeros( (labels.shape[0], labels.shape[1]+1))
        for i in range(labels.shape[0]):
            labels_appended[i] = np.concatenate((labels[i],concat))
    else:
        print("no frames")
    
    data = {
        "meta": metadata["meta"],
        "itos": metadata["itos"],
        "stoi": metadata["stoi"],
        "TextFeat": labeldata["TextFeat"],
        "frames_orig": labeldata["Text"],
        "labels_vecs": labels_appended,
        "frames_orig": framesdata["Img"],
        "frames": frames
    }

    return data

In [312]:
final_data = get_dataset_fold("train",path2embeddingdata_folder)

In [317]:
fr = final_data["frames"]
fr.shape

(97290, 65)

In [318]:
lb = final_data["labels_vecs"]
lb.shape

(97290, 201)

In [320]:
fr[[1,2,3]].shape

(3, 65)

In [341]:
vald_split = get_dataset_fold("val",path2embeddingdata_folder)

no frames


/home/magic/anaconda3/envs/basepy/lib/python3.7/site-packages/ipykernel_launcher.py:17: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


In [303]:
blah = get_dataset_fold("train",path2embeddingdata_folder)

In [304]:
blah["frames_labels_vecs"].shape

(97290, 201)

In [305]:
blah["frames_features"].shape

(97290, 65)

In [221]:
blah["frames_features"][molasses][0][0][0][0][0].shape

(65,)

In [223]:
blah["frames_features"].shape[0]

97290

In [220]:
sum(kray)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [248]:
blah["frames_labels_vecs"].shape

(1, 97290)

In [246]:
blah["frames_labels_vecs"][0][97289][0][0][2].T[0]

array([-7.2661e-01,  5.1823e-01, -6.8915e-01,  5.5925e-02, -1.1469e-01,
       -2.2319e-01,  2.8726e-01, -9.1454e-01, -3.4430e-01, -3.8494e-01,
        1.2099e-03,  1.2144e-01,  3.4518e-03, -1.7904e-01,  1.3507e-01,
        6.1024e-01, -2.4517e-01, -3.2920e-01,  3.1233e-02, -1.8997e-01,
       -1.8209e-01,  2.5278e+00, -1.8125e-01, -6.5355e-01,  8.9571e-06,
        3.2567e-01, -6.5631e-01,  2.3791e-01, -2.4090e-02,  5.5062e-01,
        2.6643e-01,  7.1802e-01, -5.4634e-01, -4.9836e-02,  2.8067e-01,
        1.9732e-01, -5.5365e-01, -7.1540e-01, -1.5462e-01, -2.2584e-01,
       -2.0502e-01, -2.4696e-01, -7.3783e-02, -3.1141e-01, -4.4872e-03,
        3.0554e-01,  1.9641e-01, -3.7167e-01,  1.6426e-01, -6.2955e-02,
        1.7643e-01, -3.6837e-01, -9.4052e-02,  1.1746e+00,  3.5042e-02,
       -3.0207e-01, -5.2314e-01,  4.1786e-01,  4.8502e-01, -1.4195e-02,
        6.7623e-02,  6.7164e-01,  1.3639e-02, -6.4965e-01, -7.2984e-02,
       -2.2502e-01,  3.1353e-01,  2.1406e-01,  3.6236e-01, -4.20

In [263]:
l = 50
bs = 6
a = np.arange(l)

In [159]:
r = l%bs
extras = bs-r
l+extras

54

In [156]:
aa= np.resize(a,l+extras)

In [160]:
aaa = np.split(aa,(l+extras)/bs)

In [165]:
Ni = 50
__batch_size = 6

In [168]:
batch_indices = np.random.permutation(Ni)
batch_indices

array([18, 39, 45, 40, 30, 12, 41, 35, 27, 19, 36, 48,  1,  3, 13, 29, 21,
       11, 46, 34, 37,  7, 16, 47, 14, 33, 32,  8, 23, 24,  5, 43,  2, 49,
       15, 22,  9, 28,  0, 38,  4, 44, 10, 42, 26, 31, 20, 17,  6, 25])

In [169]:
if Ni%__batch_size :
    padding_frames_count = __batch_size - (Ni%__batch_size)
    new_size = Ni + padding_frames_count
    batch_indices = np.resize(batch_indices, new_size)
batch_indices = batch_indices.reshape(-1, __batch_size)

In [170]:
batch_indices

array([[18, 39, 45, 40, 30, 12],
       [41, 35, 27, 19, 36, 48],
       [ 1,  3, 13, 29, 21, 11],
       [46, 34, 37,  7, 16, 47],
       [14, 33, 32,  8, 23, 24],
       [ 5, 43,  2, 49, 15, 22],
       [ 9, 28,  0, 38,  4, 44],
       [10, 42, 26, 31, 20, 17],
       [ 6, 25, 18, 39, 45, 40]])